server:
  port: 8082  # Change port from default 8080 to 9090

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice
    username: postgres
    password: pgadmin
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # maximum size per file
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8087/eureka/