server:
  port: 8081  # Change port from default 8080 to 9090

spring:
  datasource:
    url: jdbc:h2:file:./data/shopdb   # File-based H2 DB stored in ./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update   # Auto update schema on restart
    show-sql: true       # Show SQL queries in console
    properties:
      hibernate:
        format_sql: true
